# site properties and page defaults
title: johannessonlab
subtitle: 
description: An engaging 1-3 sentence description of your lab.
header: images/background.jpg
footer: images/background.jpg

# site social media and other links
links:
  email: contact@johannessonlab.com
  orcid: 0000-0001-6359-9856
  google-scholar: __qwxZoAAAAJ
  github: johannessonlab
  twitter: johannessonlab
  youtube: johannessonlab

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post
  # markdown files in /_projects - added by Markus
  - scope:
      type: "projects"
    values:
      layout: project


collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true
  # generate page for each project - added by Markus
  projects:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
